name: otogapo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+12
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animated_text_kit: ^4.2.2
  attendance_repository:
    path: packages/attendance_repository
  authentication_repository:
    path: packages/authentication_repository
  auto_route: ^7.9.2
  bloc: ^8.1.3
  carousel_slider: ^5.0.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  extended_image: ^8.2.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_flavor: ^3.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_serializable: ^6.8.0
  local_storage:
    path: packages/local_storage
  otogapo_core:
    path: packages/otogapo_core
  package_info_plus: ^8.0.0
  pocketbase: ^0.21.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  validators: ^3.0.0
  csv: ^6.0.0
  share_plus: ^10.1.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.2.5
  # Social Feed dependencies
  image: ^4.0.0
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  timeago: ^3.5.0
  path_provider: ^2.1.0
  table_calendar: ^3.0.9
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  uuid: ^4.2.2
  lottie: ^3.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
    # - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"  # Using same icon for foreground
