// ignore_for_file: public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';
// import './emergency_contact.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'vehicle.freezed.dart';
part 'vehicle.g.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
// part 'vehicle.g.dart';

@freezed
abstract class Vehicle with _$Vehicle {
  const factory Vehicle({
    String? id, // PocketBase record ID
    required String make,
    required String model,
    required num year, // PocketBase stores as number type
    required String type,
    required String color,
    required String plateNumber,
    String? primaryPhoto,
    List<String>? photos,
    String? user, // User relation field - references user ID
    // New vehicle specification fields
    num? mileage, // Vehicle mileage in km
    String? fuelType, // "Petrol", "Diesel", "Electric", "Hybrid"
    String? wheelSize, // e.g., "18-inch Alloy"
    num? maxSpeed, // Maximum speed in km/h
    String? engineDisplacement, // e.g., "2.0L", "3.5L V6"
    num? horsepower, // Engine power in HP
    String? transmission, // "Automatic", "Manual", "CVT", etc.
  }) = _Vehicle;

  factory Vehicle.fromJson(Map<String, Object?> json) => _$VehicleFromJson(json);
}
