// ignore_for_file: public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';
// import './emergency_contact.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'vehicle.freezed.dart';
part 'vehicle.g.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
// part 'vehicle.g.dart';

@freezed
abstract class Vehicle with _$Vehicle {
  const factory Vehicle({
    required String make,
    required String model,
    required String year, // Changed from int to String to match schema
    required String type,
    required String color,
    required String plateNumber,
    String? primaryPhoto,
    List<String>? photos,
    String? user, // User relation field - references user ID
  }) = _Vehicle;

  factory Vehicle.fromJson(Map<String, Object?> json) => _$VehicleFromJson(json);
}
