name: authentication_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  dio: ^5.1.2
  flutter_flavor: ^3.1.3
  freezed: ^2.5.2
  fresh: ^0.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  fresh_dio: ^0.4.0
  local_storage:
    path: ../local_storage
  freezed_annotation: ^2.4.3
  pocketbase: ^0.21.0
  url_launcher: ^6.2.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
