// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoeFfYaprCTy-ir20UulAPTyTMVtAzek0',
    appId: '1:833031029708:web:922a8c20f4f9ca282e1369',
    messagingSenderId: '833031029708',
    projectId: 'otogapo-prod',
    authDomain: 'otogapo-prod.firebaseapp.com',
    storageBucket: 'otogapo-prod.appspot.com',
    measurementId: 'G-379YFX2SFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOByf9zSlvlykYyVSgIWTa3BraI1M0AE',
    appId: '1:833031029708:android:a88967e1dc4438202e1369',
    messagingSenderId: '833031029708',
    projectId: 'otogapo-prod',
    storageBucket: 'otogapo-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_qsbfEKe_ff4kT6sWhRdjv0CPgA0qaA',
    appId: '1:833031029708:ios:54d0f7bb69825fa32e1369',
    messagingSenderId: '833031029708',
    projectId: 'otogapo-prod',
    storageBucket: 'otogapo-prod.appspot.com',
    iosBundleId: 'com.digitappstudio.otogapo',
  );
}
