// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7hhB31Oyp4K-AJcKGoQf7keo-tq14OBM',
    appId: '1:967485709855:web:beec583a41043c81037f2a',
    messagingSenderId: '967485709855',
    projectId: 'otogapo-dev',
    authDomain: 'otogapo-dev.firebaseapp.com',
    storageBucket: 'otogapo-dev.appspot.com',
    measurementId: 'G-KCQ50STJDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGqZocPXf0VjWAMp1oAgO7ytS4rpVwAM',
    appId: '1:967485709855:android:855bf69dc0b1d959037f2a',
    messagingSenderId: '967485709855',
    projectId: 'otogapo-dev',
    storageBucket: 'otogapo-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxMzyv-dOzug8Gl3M6z0HLhpFpS4cijDc',
    appId: '1:967485709855:ios:d933ad4e2dea2836037f2a',
    messagingSenderId: '967485709855',
    projectId: 'otogapo-dev',
    storageBucket: 'otogapo-dev.appspot.com',
    androidClientId: '967485709855-jgcltdks9mpi1eorkdhegbg9d72ga1cr.apps.googleusercontent.com',
    iosClientId: '967485709855-drg95nnhkanfqa9b4r4nopnt5vnc4llf.apps.googleusercontent.com',
    iosBundleId: 'com.digitappstudio.otogapo',
  );
}
