name: Manual Build

on:
    workflow_dispatch:
        inputs:
            flavor:
                description: "Build flavor"
                required: true
                default: "production"
                type: choice
                options:
                    - development
                    - staging
                    - production
            build_type:
                description: "Build type"
                required: true
                default: "apk"
                type: choice
                options:
                    - apk
                    - appbundle
                    - both

jobs:
    build:
        name: Build ${{ inputs.flavor }} (${{ inputs.build_type }})
        runs-on: ubuntu-latest
        timeout-minutes: 45

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                  distribution: "temurin"
                  java-version: "17"
                  cache: "gradle"

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.24.0"
                  channel: "stable"
                  cache: true

            - name: Install dependencies
              run: flutter pub get

            - name: Generate code
              run: dart run build_runner build --delete-conflicting-outputs

            - name: Decode keystore (Production only)
              if: inputs.flavor == 'production'
              env:
                  ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
              run: |
                  echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/keystore/otogapo-release.jks

            - name: Create key.properties (Production only)
              if: inputs.flavor == 'production'
              env:
                  KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                  KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
                  KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
              run: |
                  cat > android/key.properties << EOF
                  storeFile=keystore/otogapo-release.jks
                  storePassword=$KEYSTORE_PASSWORD
                  keyAlias=$KEY_ALIAS
                  keyPassword=$KEY_PASSWORD
                  EOF

            - name: Determine build mode
              id: build_mode
              run: |
                  if [ "${{ inputs.flavor }}" == "production" ]; then
                    echo "mode=release" >> $GITHUB_OUTPUT
                  else
                    echo "mode=debug" >> $GITHUB_OUTPUT
                  fi

            - name: Build APK
              if: inputs.build_type == 'apk' || inputs.build_type == 'both'
              run: |
                  flutter build apk \
                    --${{ steps.build_mode.outputs.mode }} \
                    --target lib/main_${{ inputs.flavor }}.dart \
                    --flavor ${{ inputs.flavor }}

            - name: Build App Bundle
              if: inputs.build_type == 'appbundle' || inputs.build_type == 'both'
              run: |
                  flutter build appbundle \
                    --${{ steps.build_mode.outputs.mode }} \
                    --target lib/main_${{ inputs.flavor }}.dart \
                    --flavor ${{ inputs.flavor }}

            - name: Upload APK artifact
              if: inputs.build_type == 'apk' || inputs.build_type == 'both'
              uses: actions/upload-artifact@v4
              with:
                  name: app-${{ inputs.flavor }}-${{ steps.build_mode.outputs.mode }}-${{ github.sha }}
                  path: build/app/outputs/flutter-apk/app-${{ inputs.flavor }}-${{ steps.build_mode.outputs.mode }}.apk
                  retention-days: 14

            - name: Upload App Bundle artifact
              if: inputs.build_type == 'appbundle' || inputs.build_type == 'both'
              uses: actions/upload-artifact@v4
              with:
                  name: bundle-${{ inputs.flavor }}-${{ steps.build_mode.outputs.mode }}-${{ github.sha }}
                  path: build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab
                  retention-days: 14

            - name: Cleanup keystore
              if: always() && inputs.flavor == 'production'
              run: |
                  rm -f android/keystore/otogapo-release.jks
                  rm -f android/key.properties
